# Generated by Django 3.2 on 2021-06-13 23:41

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Box name.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must have only alphanumeric chars and "_".', regex='^[a-z0-9]([_](?![_])|[a-z0-9])+[a-z0-9]$')], verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Box description.', verbose_name='Description')),
                ('public', models.BooleanField(help_text='If the box is public or private.', verbose_name='Public')),
                ('downloads', models.PositiveIntegerField(default=0, editable=False, help_text='Number of Downloads.', verbose_name='Downloads')),
                ('last_download_at', models.DateTimeField(editable=False, help_text='Last download time.', null=True, verbose_name='Last Download at')),
                ('creator', models.ForeignKey(help_text='Box creator.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxes',
            },
        ),
        migrations.CreateModel(
            name='BoxVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, editable=False, help_text='Box version name.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must have only alphanumeric chars and "_".', regex='^[a-z0-9]([_](?![_])|[a-z0-9])+[a-z0-9]$')], verbose_name='Name')),
                ('kind', models.CharField(choices=[('vb', 'VirtualBox'), ('lv', 'Libvirt'), ('vw', 'VMware')], help_text='Box version kind.', max_length=2, verbose_name='Kind')),
                ('description', models.TextField(blank=True, help_text='Box version description.', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Box creation time.', verbose_name='Created at')),
                ('hash', models.CharField(db_index=True, help_text='SHA1 hash of the box.', max_length=40, unique=True, verbose_name='Hash')),
                ('file', models.FileField(help_text='Box file.', max_length=255, upload_to=core.models.BoxVersion.box_version_path, verbose_name='File')),
                ('box', models.ForeignKey(help_text='Box version.', on_delete=django.db.models.deletion.CASCADE, to='core.box', verbose_name='Box Version')),
            ],
            options={
                'verbose_name': 'Box Version',
                'verbose_name_plural': 'Box Versions',
            },
        ),
    ]
